# Generated by Django 4.0.2 on 2022-03-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_no', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('mobile_no', models.BigIntegerField()),
            ],
        ),
    ]
